# Generated by Django 3.1 on 2021-03-30 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collections', '0003_auto_20200923_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecollection',
            name='created_date',
            field=models.DateField(default=datetime.date(2021, 3, 30)),
        ),
    ]
