# Generated by Django 3.1 on 2021-06-30 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collections', '0007_auto_20210628_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecollection',
            name='created_date',
            field=models.DateField(default=datetime.date(2021, 6, 30)),
        ),
    ]
