# Generated by Django 3.0.8 on 2020-08-03 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        ('movie_collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='django.util.timezone.now')),
                ('comments', models.TextField()),
                ('rating', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
                ('movie_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_collections.MovieCollection')),
            ],
        ),
    ]
