# Generated by Django 3.1 on 2020-08-16 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 16)),
        ),
    ]
