# Generated by Django 3.1 on 2021-03-30 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_item', '0003_auto_20200923_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='views',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 30)),
        ),
    ]
