# Generated by Django 3.1 on 2021-06-24 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_item', '0004_auto_20210330_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 24)),
        ),
    ]
