# Generated by Django 3.1 on 2021-06-25 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_item', '0005_auto_20210624_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 25)),
        ),
    ]
