# Generated by Django 3.1 on 2021-06-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sci_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
