# Generated by Django 3.1 on 2021-06-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_type', '0001_initial'),
        ('plant', '0003_auto_20210625_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='type',
        ),
        migrations.AddField(
            model_name='plant',
            name='types',
            field=models.ManyToManyField(to='plant_type.PlantType'),
        ),
    ]
