# Generated by Django 3.0.8 on 2020-08-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmbd_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
            ],
        ),
    ]
