# Generated by Django 3.0.8 on 2020-08-03 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tmbd_id',
            new_name='tmdb_id',
        ),
    ]
