# Generated by Django 3.1 on 2021-02-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200923_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_prefix',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
