# Generated by Django 3.1 on 2021-06-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_item', '0002_auto_20210624_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantitem',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
